name: williamjohnsonphotography
favicon: null
layout_spectrum: 0.7465917540248483
typography_spectrum: 0.45980344270356
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.007322786608710885
  lightness: 0.6848387180361897
  saturation: 0.8953635757789016
  rhythmicContrast: 0.016960902139544487
purpose: []
